<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Enter' => 'Edition',
  'Select' => 'Sélection',
  'You should provide modelClass in constructor of EditableSaver.'=>'La classe du modèle doit être donné en tant que paramètre au constructeur d\'EditableSaver',
  'Property "attribute" should be defined.'=>'La propriété "attribute" doit être définie',
  'Property "primaryKey" should be defined.'=>'La propriété "primaryKey" doit être définie',
  'Model {class} not found by primary key "{pk}"'=>'Le modèle {class} n\'est pas trouvé pour la clef primaire "{pk}"',
  'Model {class} does not have attribute "{attr}"'=>'Le modèle {class} ne possède pas l\'attribut "{attr}"',
  'Model {class} rules do not allow to update attribute "{attr}"'=>'Le modèle {class} n\'autorise pas la mise à jour de l\'attribut "{attr}"',
  'Error while saving record!'=>'Erreur lors de la sauvegarde!',

);
